### ISSUE TITLE
Incorrect Bibliography Entries

### ISSUE THREAD

**Issue by Venyla** [sa-concept-refactoring/doc#105]
Two different entries with the same title...

![Image](https://github.com/sa-concept-refactoring/doc/assets/6904387/237a0f42-5de9-4f11-83bf-ba0d189d4026)

**Comment by jeremystucki** [comment]
uups

**Comment by jeremystucki** [comment]
Done in 19498b57e1df39cbfa76d9d6ee3eb1f82d8938a2
