### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by jeremystucki** [sa-concept-refactoring/doc#51]
- [ ] Ufgabestellig ahhenke (für online version **ohni Unterschrift** => ned in git ihchecke)
- [ ] Declaration of Athorship

Zeiterfassung & Weekly Updates:
Corbat in Teams - "Müsst ihr nicht in den Anhang packen. Im Abgabearchiv reicht es."

**Comment by Venyla** [comment]
[Assignment.pdf](https://github.com/sa-concept-refactoring/doc/files/13673386/Assignment.pdf)
[Assignment ohne Unterschrift.pdf](https://github.com/sa-concept-refactoring/doc/files/13673385/Assignment.ohne.Unterschrift.pdf)

**Comment by jeremystucki** [comment]
also bim usdruck mit unterschrift aber bim online ohni?
